version: '3.9'

services:
  polls_flask:
    container_name: polls_flask
    build: .
    ports:
    - 8080:5000
    volumes:
    - ./:/app
    environment:
    - FLASK_ENV=development
    depends_on:
    - polls_db
    networks:
    - pollsNetwork

  polls_db:
    container_name: polls_db
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - pollsDbVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: polls
      POSTGRES_USER: polls
      POSTGRES_PASSWORD: secret
    networks:
    - pollsNetwork

volumes:
  pollsDbVolume:
    driver: local


networks:
  pollsNetwork:
    driver: "bridge"
